# PostgreSQL ConfigMap Configuration
# This file defines a Kubernetes ConfigMap for the PostgreSQL database
# A ConfigMap provides a way to inject configuration data into pods

apiVersion: v1 # The API version for ConfigMap resources
kind: ConfigMap # The type of Kubernetes resource
metadata: # Metadata about the ConfigMap
  name: postgres-config # The name of this ConfigMap
  labels: # Labels to identify this resource
    app: postgres # Label that identifies this as part of the PostgreSQL application
data: # The actual configuration data
  # These environment variables will be used by the PostgreSQL container
  POSTGRES_USER: postgres # The username for the PostgreSQL database
  POSTGRES_PASSWORD: postgres # The password for the PostgreSQL database (in production, use Secrets instead)
  POSTGRES_DB: monorepo # The name of the database to create


  # Note: For production environments, it's recommended to use Kubernetes Secrets
  # instead of ConfigMaps for sensitive data like passwords
