# PostgreSQL ConfigMap Configuration
# This file defines a Kubernetes ConfigMap for the PostgreSQL database
# A ConfigMap provides a way to inject configuration data into pods

apiVersion: v1 # The API version for ConfigMap resources
kind: ConfigMap # The type of Kubernetes resource
metadata: # Metadata about the ConfigMap
  name: postgres-config # The name of this ConfigMap
  labels: # Labels to identify this resource
    app: postgres # Label that identifies this as part of the PostgreSQL application
data: # The actual configuration data
  # These environment variables will be used by the PostgreSQL container
  POSTGRES_DB: monorepo # The name of the database to create
