apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  # The connection string used by the API and migration job
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/monorepo
