apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: monorepo-app
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        timestamp: "${TIMESTAMP}"
    spec:
      containers:
        - name: api
          image: ${REGISTRY_URL}/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: NODE_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
