apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monorepo-app

resources:
  - namespace.yaml
  - web-deployment.yaml
  - web-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: monorepo-app

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
