# Production API Secrets Patch
# This file patches the base API secrets for production use
# In a real production environment, you would use a secret management solution
# like Vault, AWS Secrets Manager, or Sealed Secrets instead of this approach

apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    environment: production
type: Opaque
stringData:
  # These are example values - in a real production environment,
  # you would use a more secure approach to manage these secrets
  BETTER_AUTH_SECRET: ${AUTH_SECRET} # This will be replaced during deployment
