# Production PostgreSQL Secrets Patch
# This file patches the base PostgreSQL secrets for production use
# In a real production environment, you would use a secret management solution
# like Vault, AWS Secrets Manager, or Sealed Secrets instead of this approach

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    environment: production
type: Opaque
stringData:
  # These are example values - in a real production environment,
  # you would use a more secure approach to manage these secrets
  POSTGRES_USER: postgres_prod
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # This will be replaced during deployment
  DATABASE_URL: postgresql://postgres_prod:${POSTGRES_PASSWORD}@postgres:5432/monorepo_prod
