name: Publish Docker Images to GHCR

on:
  push:
    branches: [main]
    # Publish semver tags as releases
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  # Use docker.io for Docker Hub if needed
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME_WEB: ${{ github.repository }}-web
  IMAGE_NAME_API: ${{ github.repository }}-api

jobs:
  # Split into two parallel jobs
  build-and-push-web:
    name: Build and Push Web Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is needed for requesting the JWT
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # Login to GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker images
      - name: Extract Docker metadata for Web
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # Build and push Web Docker image
      - name: Build and push Web Docker image
        id: build-and-push-web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-api:
    name: Build and Push API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is needed for requesting the JWT
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # Login to GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for Docker images
      - name: Extract Docker metadata for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # Build and push API Docker image
      - name: Build and push API Docker image
        id: build-and-push-api
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Summary job that runs after both builds are complete
  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-and-push-web, build-and-push-api]
    if: always()

    steps:
      - name: Check build status
        run: |
          if [[ "${{ needs.build-and-push-web.result }}" != "success" || "${{ needs.build-and-push-api.result }}" != "success" ]]; then
            echo "::error::One or more builds failed!"
            echo "Web build status: ${{ needs.build-and-push-web.result }}"
            echo "API build status: ${{ needs.build-and-push-api.result }}"
            exit 1
          else
            echo "::notice::All builds completed successfully!"
            echo "Web build status: ${{ needs.build-and-push-web.result }}"
            echo "API build status: ${{ needs.build-and-push-api.result }}"

            echo "Images are now available at:"
            echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}"
            echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}"
          fi
